Neos:
  ContentRepository:
    Search:
      defaultContext:
        Indexing: Flowpack\ElasticSearch\ContentGraphAdapter\Eel\IndexingHelper

Flowpack:
  ElasticSearch:
    ContentGraphAdapter:
      indexing:
        workspaceIndexingMode: onlyLive
